spring:
  profiles: common
wx:
  app-id: your_secret_key
  app-secret: your_secret_key
  mch-id: your_secret_key
  key: your_secret_key
  cert-path: E:\apiclient_cert.p12
tencent:
  cloud:
    appId: 1309952305
    secretId: your_secret_key
    secretKey: your_secret_key
    region-public: beijing
    bucket-public: your_secret_key
    region-private: beijing
    bucket-private: your_secret_key
    face:
      groupName: hxds
      region: ap-beijing

  map:
    key: your_secret_key

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456

hxds:
  tcode: "你的tocde必须写到双引号里面"
  icode: 你的icode
  key: your_secret_key
  privateKey: your_secret_key
  publicKey: your_secret_key